# Generated by Django 5.2.1 on 2025-05-17 18:35

import cinema.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_moviesession_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviesession",
            name="image",
            field=models.ImageField(
                null=True, upload_to=cinema.models.movie_image_path
            ),
        ),
    ]
