# Generated by Django 5.2.1 on 2025-05-18 17:07

import cinema.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0003_alter_moviesession_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=cinema.models.movie_image_path
            ),
        ),
    ]
